### PR TITLE
Composition.vr

### PR DESCRIPTION
**Pull request by AlexKBADPMC**
This mission-file contains all compositions used and unused in OPCB. Map is Virtual Reality and has all the comps build in there.

### CODE REVIEW

**Comment by KHunter-Arma** [comment]
Is this just for developing compositions? Otherwise if it's for putting into the mission, why don't we just have separate composition files instead of a mission.sqm? I don't understand what this PR is for

**Comment by AlexKBADPMC** [comment]
Yeah, should have added, what this is about. It's for developing compositions. The file contains all the compositions, that have been build for OPCB so far!

**Comment by AlexKBADPMC** [comment]
Giving access to this file should allow all Devs to improve/fix existing compositions, do joint builds or share among all of us. But if deemed not needed, this can be rejected!

**Comment by KHunter-Arma** [comment]
Ah alright, it actually sounds like quite a decent idea then! The only "issue" is, it shouldn't be under mission-files. We should have a separate folder for this and perhaps we can include more things under that folder in the future. Perhaps a "compositions" or "comps" folder

**Pull request closed without merging**
